In [1]:
! pip install ultralytics


[notice] A new release of pip is available: 23.2.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import os
import random
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import cv2
from shutil import copyfile
import csv
import shutil
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from ultralytics import YOLO

C:\Users\Genius\AppData\Local\Temp\ipykernel_10340\2153776174.py:3: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
# Load a model
model = YOLO('yolov8n-cls.pt')  # load a pretrained model (recommended for training)

data = "E:/Clg Activities/Projects/Cosmetic shade recomender/Data"
# Train the model
model.train(data=data , epochs=60)

Ultralytics 8.3.31  Python-3.12.1 torch-2.5.1+cpu CPU (Intel Core(TM) i5-6300U 2.40GHz)
engine\trainer: task=classify, mode=train, model=yolov8n-cls.pt, data=E:/Clg Activities/Projects/Cosmetic shade recomender/Data, epochs=60, time=None, patience=100, batch=16, imgsz=224, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train30, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False,

train: Scanning E:\Clg Activities\Projects\Cosmetic shade recomender\Data\train... 1025 images, 0 corrupt: 100%|██████████| 1025/1025 [00:00<?, ?it/s]
val: Scanning E:\Clg Activities\Projects\Cosmetic shade recomender\Data\validation... 314 images, 0 corrupt: 100%|██████████| 314/314 [00:00<?, ?it/s]


optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.000714, momentum=0.9) with parameter groups 26 weight(decay=0.0), 27 weight(decay=0.0005), 27 bias(decay=0.0)
TensorBoard: model graph visualization added 
Image sizes 224 train, 224 val
Using 0 dataloader workers
Logging results to runs\classify\train30
Starting training for 60 epochs...

      Epoch    GPU_mem       loss  Instances       Size


               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.30it/s]

                   all        0.5          1



      Epoch    GPU_mem       loss  Instances       Size


               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.33it/s]

                   all      0.554          1



      Epoch    GPU_mem       loss  Instances       Size


               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:08<00:00,  1.16it/s]

                   all      0.513          1



      Epoch    GPU_mem       loss  Instances       Size


               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.37it/s]

                   all      0.777          1



      Epoch    GPU_mem       loss  Instances       Size


               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:06<00:00,  1.47it/s]

                   all      0.774          1



      Epoch    GPU_mem       loss  Instances       Size


               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.34it/s]

                   all      0.742          1



      Epoch    GPU_mem       loss  Instances       Size


               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.35it/s]

                   all      0.742          1



      Epoch    GPU_mem       loss  Instances       Size


               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.38it/s]

                   all      0.783          1



      Epoch    GPU_mem       loss  Instances       Size


               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.35it/s]

                   all      0.742          1



      Epoch    GPU_mem       loss  Instances       Size


      10/60         0G     0.6392          1        224: 100%|██████████| 65/65 [01:16<00:00,  1.18s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.34it/s]

                   all      0.803          1



      Epoch    GPU_mem       loss  Instances       Size


      11/60         0G     0.5467          1        224: 100%|██████████| 65/65 [01:12<00:00,  1.11s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.36it/s]

                   all      0.822          1



      Epoch    GPU_mem       loss  Instances       Size


      12/60         0G     0.4913          1        224: 100%|██████████| 65/65 [01:09<00:00,  1.08s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:05<00:00,  1.80it/s]

                   all      0.764          1



      Epoch    GPU_mem       loss  Instances       Size


      13/60         0G     0.4759          1        224: 100%|██████████| 65/65 [00:47<00:00,  1.36it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:04<00:00,  2.11it/s]

                   all      0.793          1



      Epoch    GPU_mem       loss  Instances       Size


      14/60         0G     0.4908          1        224: 100%|██████████| 65/65 [00:44<00:00,  1.47it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:04<00:00,  2.03it/s]

                   all      0.793          1



      Epoch    GPU_mem       loss  Instances       Size


      15/60         0G     0.4642          1        224: 100%|██████████| 65/65 [00:44<00:00,  1.46it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:04<00:00,  2.03it/s]

                   all      0.774          1



      Epoch    GPU_mem       loss  Instances       Size


      16/60         0G     0.4844          1        224: 100%|██████████| 65/65 [00:49<00:00,  1.32it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:05<00:00,  1.97it/s]

                   all       0.79          1



      Epoch    GPU_mem       loss  Instances       Size


      17/60         0G     0.4552          1        224: 100%|██████████| 65/65 [00:53<00:00,  1.21it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.40it/s]

                   all      0.796          1



      Epoch    GPU_mem       loss  Instances       Size


      18/60         0G     0.4497          1        224: 100%|██████████| 65/65 [00:51<00:00,  1.25it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:05<00:00,  1.83it/s]

                   all      0.828          1



      Epoch    GPU_mem       loss  Instances       Size


      19/60         0G     0.4024          1        224: 100%|██████████| 65/65 [00:51<00:00,  1.27it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:04<00:00,  2.09it/s]

                   all      0.831          1



      Epoch    GPU_mem       loss  Instances       Size


      20/60         0G     0.4206          1        224: 100%|██████████| 65/65 [01:02<00:00,  1.04it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.40it/s]

                   all       0.78          1



      Epoch    GPU_mem       loss  Instances       Size


      21/60         0G     0.3961          1        224: 100%|██████████| 65/65 [01:20<00:00,  1.24s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.33it/s]

                   all       0.78          1



      Epoch    GPU_mem       loss  Instances       Size


      22/60         0G     0.3893          1        224: 100%|██████████| 65/65 [01:13<00:00,  1.13s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:06<00:00,  1.43it/s]

                   all      0.809          1



      Epoch    GPU_mem       loss  Instances       Size


      23/60         0G     0.3982          1        224: 100%|██████████| 65/65 [01:14<00:00,  1.15s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.36it/s]

                   all      0.799          1



      Epoch    GPU_mem       loss  Instances       Size


      24/60         0G     0.3366          1        224: 100%|██████████| 65/65 [01:09<00:00,  1.07s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.37it/s]

                   all      0.825          1



      Epoch    GPU_mem       loss  Instances       Size


      25/60         0G     0.3578          1        224: 100%|██████████| 65/65 [01:17<00:00,  1.19s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.30it/s]

                   all      0.812          1



      Epoch    GPU_mem       loss  Instances       Size


      26/60         0G      0.327          1        224: 100%|██████████| 65/65 [01:13<00:00,  1.12s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:08<00:00,  1.17it/s]

                   all      0.806          1



      Epoch    GPU_mem       loss  Instances       Size


      27/60         0G     0.3278          1        224: 100%|██████████| 65/65 [01:10<00:00,  1.09s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.40it/s]

                   all      0.812          1



      Epoch    GPU_mem       loss  Instances       Size


      28/60         0G     0.3434          1        224: 100%|██████████| 65/65 [01:12<00:00,  1.11s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:06<00:00,  1.47it/s]

                   all      0.806          1



      Epoch    GPU_mem       loss  Instances       Size


      29/60         0G     0.3663          1        224: 100%|██████████| 65/65 [01:04<00:00,  1.00it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:06<00:00,  1.47it/s]

                   all      0.803          1



      Epoch    GPU_mem       loss  Instances       Size


      30/60         0G     0.3567          1        224: 100%|██████████| 65/65 [01:08<00:00,  1.06s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.40it/s]

                   all      0.806          1



      Epoch    GPU_mem       loss  Instances       Size


      31/60         0G     0.2756          1        224: 100%|██████████| 65/65 [01:18<00:00,  1.21s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.32it/s]

                   all      0.812          1



      Epoch    GPU_mem       loss  Instances       Size


      32/60         0G     0.3077          1        224: 100%|██████████| 65/65 [01:11<00:00,  1.10s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.38it/s]

                   all      0.822          1



      Epoch    GPU_mem       loss  Instances       Size


      33/60         0G      0.355          1        224: 100%|██████████| 65/65 [01:14<00:00,  1.14s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:08<00:00,  1.21it/s]

                   all      0.815          1



      Epoch    GPU_mem       loss  Instances       Size


      34/60         0G     0.3105          1        224: 100%|██████████| 65/65 [01:16<00:00,  1.18s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.33it/s]

                   all      0.809          1



      Epoch    GPU_mem       loss  Instances       Size


      35/60         0G     0.2848          1        224: 100%|██████████| 65/65 [01:16<00:00,  1.18s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.34it/s]

                   all      0.799          1



      Epoch    GPU_mem       loss  Instances       Size


      36/60         0G     0.3239          1        224: 100%|██████████| 65/65 [01:13<00:00,  1.14s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.34it/s]

                   all      0.803          1



      Epoch    GPU_mem       loss  Instances       Size


      37/60         0G     0.2652          1        224: 100%|██████████| 65/65 [02:04<00:00,  1.92s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:10<00:00,  1.05s/it]

                   all      0.818          1



      Epoch    GPU_mem       loss  Instances       Size


      38/60         0G     0.2805          1        224: 100%|██████████| 65/65 [01:26<00:00,  1.33s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.34it/s]

                   all      0.809          1



      Epoch    GPU_mem       loss  Instances       Size


      39/60         0G     0.2594          1        224: 100%|██████████| 65/65 [01:19<00:00,  1.22s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.26it/s]

                   all      0.822          1



      Epoch    GPU_mem       loss  Instances       Size


      40/60         0G     0.2443          1        224: 100%|██████████| 65/65 [01:19<00:00,  1.22s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:08<00:00,  1.25it/s]

                   all      0.796          1



      Epoch    GPU_mem       loss  Instances       Size


      41/60         0G     0.2888          1        224: 100%|██████████| 65/65 [01:13<00:00,  1.13s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.36it/s]

                   all      0.818          1



      Epoch    GPU_mem       loss  Instances       Size


      42/60         0G     0.2386          1        224: 100%|██████████| 65/65 [01:12<00:00,  1.11s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.38it/s]

                   all      0.812          1



      Epoch    GPU_mem       loss  Instances       Size


      43/60         0G     0.2182          1        224: 100%|██████████| 65/65 [01:11<00:00,  1.11s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.39it/s]

                   all      0.838          1



      Epoch    GPU_mem       loss  Instances       Size


      44/60         0G     0.2954          1        224: 100%|██████████| 65/65 [01:15<00:00,  1.16s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:08<00:00,  1.24it/s]

                   all      0.818          1



      Epoch    GPU_mem       loss  Instances       Size


      45/60         0G     0.2379          1        224: 100%|██████████| 65/65 [01:12<00:00,  1.11s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.39it/s]

                   all      0.809          1



      Epoch    GPU_mem       loss  Instances       Size


      46/60         0G     0.2857          1        224: 100%|██████████| 65/65 [01:12<00:00,  1.12s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.37it/s]

                   all      0.809          1



      Epoch    GPU_mem       loss  Instances       Size


      47/60         0G     0.2142          1        224: 100%|██████████| 65/65 [01:15<00:00,  1.16s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.31it/s]

                   all      0.815          1



      Epoch    GPU_mem       loss  Instances       Size


      48/60         0G     0.2214          1        224: 100%|██████████| 65/65 [01:17<00:00,  1.19s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.35it/s]

                   all      0.834          1



      Epoch    GPU_mem       loss  Instances       Size


      49/60         0G     0.2425          1        224: 100%|██████████| 65/65 [01:15<00:00,  1.16s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.35it/s]

                   all      0.828          1



      Epoch    GPU_mem       loss  Instances       Size


      50/60         0G     0.2367          1        224: 100%|██████████| 65/65 [01:13<00:00,  1.13s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.31it/s]

                   all      0.828          1



      Epoch    GPU_mem       loss  Instances       Size


      51/60         0G     0.2326          1        224: 100%|██████████| 65/65 [01:17<00:00,  1.19s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.37it/s]

                   all      0.825          1



      Epoch    GPU_mem       loss  Instances       Size


      52/60         0G     0.1949          1        224: 100%|██████████| 65/65 [01:14<00:00,  1.14s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.32it/s]

                   all      0.831          1



      Epoch    GPU_mem       loss  Instances       Size


      53/60         0G     0.1731          1        224: 100%|██████████| 65/65 [01:18<00:00,  1.20s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.29it/s]

                   all      0.831          1



      Epoch    GPU_mem       loss  Instances       Size


      54/60         0G     0.1974          1        224: 100%|██████████| 65/65 [01:20<00:00,  1.24s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:08<00:00,  1.21it/s]

                   all      0.828          1



      Epoch    GPU_mem       loss  Instances       Size


      55/60         0G      0.221          1        224: 100%|██████████| 65/65 [01:20<00:00,  1.23s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.31it/s]

                   all      0.831          1



      Epoch    GPU_mem       loss  Instances       Size


      56/60         0G     0.2074          1        224: 100%|██████████| 65/65 [01:20<00:00,  1.24s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:08<00:00,  1.25it/s]

                   all      0.831          1



      Epoch    GPU_mem       loss  Instances       Size


      57/60         0G     0.1933          1        224: 100%|██████████| 65/65 [01:16<00:00,  1.18s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.35it/s]

                   all      0.825          1



      Epoch    GPU_mem       loss  Instances       Size


      58/60         0G     0.2166          1        224: 100%|██████████| 65/65 [01:12<00:00,  1.12s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.34it/s]

                   all      0.831          1



      Epoch    GPU_mem       loss  Instances       Size


      59/60         0G     0.2137          1        224: 100%|██████████| 65/65 [01:12<00:00,  1.11s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.31it/s]

                   all      0.825          1



      Epoch    GPU_mem       loss  Instances       Size


      60/60         0G     0.2229          1        224: 100%|██████████| 65/65 [01:11<00:00,  1.10s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.27it/s]

                   all      0.822          1



60 epochs completed in 1.572 hours.
Optimizer stripped from runs\classify\train30\weights\last.pt, 3.0MB
Optimizer stripped from runs\classify\train30\weights\best.pt, 3.0MB

Validating runs\classify\train30\weights\best.pt...
Ultralytics 8.3.31  Python-3.12.1 torch-2.5.1+cpu CPU (Intel Core(TM) i5-6300U 2.40GHz)
YOLOv8n-cls summary (fused): 73 layers, 1,441,285 parameters, 0 gradients, 3.3 GFLOPs
train: E:\Clg Activities\Projects\Cosmetic shade recomender\Data\train... found 1025 images in 5 classes  
val: E:\Clg Activities\Projects\Cosmetic shade recomender\Data\validation... found 314 images in 5 classes  
test: E:\Clg Activities\Projects\Cosmetic shade recomender\Data\test... found 173 images in 5 classes  


               classes   top1_acc   top5_acc: 100%|██████████| 10/10 [00:07<00:00,  1.43it/s]


                   all      0.838          1
Speed: 0.0ms preprocess, 12.1ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to runs\classify\train30


ultralytics.utils.metrics.ClassifyMetrics object with attributes:

confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x00000293DABAD520>
curves: []
curves_results: []
fitness: 0.918789803981781
keys: ['metrics/accuracy_top1', 'metrics/accuracy_top5']
results_dict: {'metrics/accuracy_top1': 0.837579607963562, 'metrics/accuracy_top5': 1.0, 'fitness': 0.918789803981781}
save_dir: WindowsPath('runs/classify/train30')
speed: {'preprocess': 0.0, 'inference': 12.051134352471419, 'loss': 0.0, 'postprocess': 0.0}
task: 'classify'
top1: 0.837579607963562
top5: 1.0

In [3]:
# Load the trained model
trained_model = YOLO(r'E:\Clg Activities\Projects\Cosmetic shade recomender\Project code\runs\classify\train30\weights\best.pt')  # Replace with the path to your best model

In [4]:
# Run inference on a test image
results = trained_model.predict(source=r"E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Dark", batch = 5)
print(results)


image 1/21 E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Dark\1 - Copy.jpeg: 224x224 Dark 1.00, Medium Dark 0.00, Medium 0.00, Very Fair 0.00, Fair 0.00, 23.7ms
image 2/21 E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Dark\10.jpg: 224x224 Dark 1.00, Medium Dark 0.00, Medium 0.00, Very Fair 0.00, Fair 0.00, 23.7ms
image 3/21 E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Dark\12.jpg: 224x224 Dark 1.00, Fair 0.00, Medium 0.00, Very Fair 0.00, Medium Dark 0.00, 23.7ms
image 4/21 E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Dark\14 - Copy.jpg: 224x224 Dark 1.00, Medium Dark 0.00, Medium 0.00, Very Fair 0.00, Fair 0.00, 23.7ms
image 5/21 E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Dark\19 - Copy.jpeg: 224x224 Dark 1.00, Medium Dark 0.00, Medium 0.00, Very Fair 0.00, Fair 0.00, 23.7ms
image 6/21 E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Dark\24_1_1_20170112204648604.jpg.chip.jpg: 224x

# Prediction on training data and cm 

In [5]:
# Prediction on training data and cm


true_labels = []
predicted_labels = []

# Run inference on each class and collect true and predicted labels
    
# Class 0: Dark
results = trained_model.predict(source="E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Dark")
for result in results:
    predicted_class = result.probs.top1  # Get the predicted class index
    true_labels.append(0)  # Dark corresponds to label 0
    predicted_labels.append(predicted_class)

# Class 1: Fair
results1 = trained_model.predict(source='E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Fair')
for result in results1:
    predicted_class = result.probs.top1  # Get the predicted class index
    true_labels.append(1)  # Fair corresponds to label 2
    predicted_labels.append(predicted_class)

# Class 2: Medium
results2 = trained_model.predict(source='E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Medium')
for result in results2:
    predicted_class = result.probs.top1  # Get the predicted class index
    true_labels.append(2)  # Medium corresponds to label 3
    predicted_labels.append(predicted_class)

# Class 3: Medium Dark
results = trained_model.predict(source="E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Medium Dark")
for result in results:
    predicted_class = result.probs.top1  # Get the predicted class index
    true_labels.append(3)  # Medium Dark corresponds to label 4
    predicted_labels.append(predicted_class)

# Class 4: Very Fair
results = trained_model.predict(source="E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Very Fair")
for result in results:
    predicted_class = result.probs.top1  # Get the predicted class index
    true_labels.append(4)  # BaVery Fair corresponds to label 5
    predicted_labels.append(predicted_class)

    
# Now you have true_labels and predicted_labels lists
print(true_labels)
print(predicted_labels)


image 1/21 E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Dark\1 - Copy.jpeg: 224x224 Dark 1.00, Medium Dark 0.00, Medium 0.00, Very Fair 0.00, Fair 0.00, 48.9ms


<>:10: SyntaxWarning: invalid escape sequence '\C'
<>:17: SyntaxWarning: invalid escape sequence '\C'
<>:24: SyntaxWarning: invalid escape sequence '\C'
<>:31: SyntaxWarning: invalid escape sequence '\C'
<>:38: SyntaxWarning: invalid escape sequence '\C'
<>:10: SyntaxWarning: invalid escape sequence '\C'
<>:17: SyntaxWarning: invalid escape sequence '\C'
<>:24: SyntaxWarning: invalid escape sequence '\C'
<>:31: SyntaxWarning: invalid escape sequence '\C'
<>:38: SyntaxWarning: invalid escape sequence '\C'
C:\Users\Genius\AppData\Local\Temp\ipykernel_10340\747146705.py:10: SyntaxWarning: invalid escape sequence '\C'
  results = trained_model.predict(source="E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Dark")
C:\Users\Genius\AppData\Local\Temp\ipykernel_10340\747146705.py:17: SyntaxWarning: invalid escape sequence '\C'
  results1 = trained_model.predict(source='E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Fair')
C:\Users\Genius\AppData\Local\Temp\ipyker

image 2/21 E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Dark\10.jpg: 224x224 Dark 1.00, Medium Dark 0.00, Medium 0.00, Very Fair 0.00, Fair 0.00, 148.6ms
image 3/21 E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Dark\12.jpg: 224x224 Dark 1.00, Fair 0.00, Medium 0.00, Very Fair 0.00, Medium Dark 0.00, 79.8ms
image 4/21 E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Dark\14 - Copy.jpg: 224x224 Dark 1.00, Medium Dark 0.00, Medium 0.00, Very Fair 0.00, Fair 0.00, 38.9ms
image 5/21 E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Dark\19 - Copy.jpeg: 224x224 Dark 1.00, Medium Dark 0.00, Medium 0.00, Very Fair 0.00, Fair 0.00, 39.9ms
image 6/21 E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Dark\24_1_1_20170112204648604.jpg.chip.jpg: 224x224 Dark 1.00, Medium Dark 0.00, Medium 0.00, Very Fair 0.00, Fair 0.00, 55.9ms
image 7/21 E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Test\Dark\25.jpg: 224x224 Dar

In [6]:
# Define class names
class_names = ["Dark", "Fair", "Medium","Medium Dark","Very Fair"]

# Compute the confusion matrix
conf_matrix = confusion_matrix(true_labels, predicted_labels)
print(conf_matrix)
# Plot the confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

[[21  0  0  0  0]
 [ 0 37  2  0  2]
 [ 0  0 33  2  0]
 [ 4  0 14 14  0]
 [ 0 13  1  0 30]]


<Figure size 800x600 with 2 Axes>

# Prediction on validation data and cm 

In [7]:
true_labels = []
predicted_labels = []

# Run inference on each class and collect true and predicted labels
    
# Class 1: Dark
results = trained_model.predict(source='E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Validation\Dark')
for result in results:
    predicted_class = result.probs.top1  # Get the predicted class index
    true_labels.append(0)  # Badminton corresponds to label 0
    predicted_labels.append(predicted_class)

# Class 2: Fair
results1 = trained_model.predict(source='E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Validation\Fair')
for result in results1:
    predicted_class = result.probs.top1  # Get the predicted class index
    true_labels.append(1)  # Cricket corresponds to label 1
    predicted_labels.append(predicted_class)

# Class 3: Medium
results2 = trained_model.predict(source='E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Validation\Medium')
for result in results2:
    predicted_class = result.probs.top1  # Get the predicted class index
    true_labels.append(2)  # Football corresponds to label 2
    predicted_labels.append(predicted_class)

# Class 4: Medium dark
results2 = trained_model.predict(source='E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Validation\Medium Dark')
for result in results2:
    predicted_class = result.probs.top1  # Get the predicted class index
    true_labels.append(3)  # Football corresponds to label 2
    predicted_labels.append(predicted_class)

# Class 5: MVery fair
results2 = trained_model.predict(source='E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Validation\Very Fair')
for result in results2:
    predicted_class = result.probs.top1  # Get the predicted class index
    true_labels.append(4)  # Football corresponds to label 2
    predicted_labels.append(predicted_class)
    
# Now you have true_labels and predicted_labels lists
print(true_labels)
print(predicted_labels)


image 1/38 E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Validation\Dark\1 - Copy.jpeg: 224x224 Dark 1.00, Medium Dark 0.00, Medium 0.00, Very Fair 0.00, Fair 0.00, 62.8ms


<>:7: SyntaxWarning: invalid escape sequence '\C'
<>:14: SyntaxWarning: invalid escape sequence '\C'
<>:21: SyntaxWarning: invalid escape sequence '\C'
<>:28: SyntaxWarning: invalid escape sequence '\C'
<>:35: SyntaxWarning: invalid escape sequence '\C'
<>:7: SyntaxWarning: invalid escape sequence '\C'
<>:14: SyntaxWarning: invalid escape sequence '\C'
<>:21: SyntaxWarning: invalid escape sequence '\C'
<>:28: SyntaxWarning: invalid escape sequence '\C'
<>:35: SyntaxWarning: invalid escape sequence '\C'
C:\Users\Genius\AppData\Local\Temp\ipykernel_10340\660512413.py:7: SyntaxWarning: invalid escape sequence '\C'
  results = trained_model.predict(source='E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Validation\Dark')
C:\Users\Genius\AppData\Local\Temp\ipykernel_10340\660512413.py:14: SyntaxWarning: invalid escape sequence '\C'
  results1 = trained_model.predict(source='E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Validation\Fair')
C:\Users\Genius\AppData\Local\Te

image 2/38 E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Validation\Dark\15 - Copy.jpg: 224x224 Dark 1.00, Medium Dark 0.00, Medium 0.00, Very Fair 0.00, Fair 0.00, 219.4ms
image 3/38 E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Validation\Dark\15_0_1_20170120134502877.jpg.chip (2).jpg: 224x224 Dark 0.98, Medium Dark 0.02, Medium 0.00, Very Fair 0.00, Fair 0.00, 71.8ms
image 4/38 E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Validation\Dark\19 - Copy.jpeg: 224x224 Dark 1.00, Medium Dark 0.00, Medium 0.00, Very Fair 0.00, Fair 0.00, 88.8ms
image 5/38 E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Validation\Dark\19.jpeg: 224x224 Dark 1.00, Medium Dark 0.00, Medium 0.00, Very Fair 0.00, Fair 0.00, 113.7ms
image 6/38 E:\Clg Activities\Projects\Cosmetic shade recomender\Data\Validation\Dark\24_1_1_20170112204648604.jpg.chip - Copy.jpg: 224x224 Dark 1.00, Medium Dark 0.00, Medium 0.00, Very Fair 0.00, Fair 0.00, 41.9ms
image 7/38 E:\Clg Activi

In [8]:
# Define class names
class_names = ["Dark", "Fair", "Medium","Medium Dark","Very Fair"]

# Compute the confusion matrix
conf_matrix = confusion_matrix(true_labels, predicted_labels)
print(conf_matrix)
# Plot the confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Reds', xticklabels=class_names, yticklabels=class_names)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

[[38  0  0  0  0]
 [ 0 44  8  0  7]
 [ 0  2 61  2  0]
 [ 4  0 14 46  0]
 [ 0 13  1  0 74]]


<Figure size 800x600 with 2 Axes>

In [9]:
from sklearn.metrics import classification_report
import numpy as np

# Given confusion matrix
conf_matrix = np.array([
    [38, 0, 0, 0, 0],
    [0, 44, 8, 0, 7],
    [0, 2, 61, 2, 0],
    [4, 0, 14, 46, 0],
    [0, 13, 1, 0, 74]
])

# Generate true labels and predicted labels
true_labels = []
pred_labels = []
for actual_class in range(conf_matrix.shape[0]):
    for predicted_class in range(conf_matrix.shape[1]):
        count = conf_matrix[actual_class, predicted_class]
        true_labels.extend([actual_class] * count)
        pred_labels.extend([predicted_class] * count)

# Class names (optional, replace with your class names if needed)
class_names = ["Dark", "Fair", "Medium", "Medium Dark", "Very Fair"]

# Generate classification report
report = classification_report(true_labels, pred_labels, target_names=class_names)

print("Classification Report:")
print(report)


Classification Report:
              precision    recall  f1-score   support

        Dark       0.90      1.00      0.95        38
        Fair       0.75      0.75      0.75        59
      Medium       0.73      0.94      0.82        65
 Medium Dark       0.96      0.72      0.82        64
   Very Fair       0.91      0.84      0.88        88

    accuracy                           0.84       314
   macro avg       0.85      0.85      0.84       314
weighted avg       0.85      0.84      0.84       314

